### ISSUE TITLE
Create simple UI for search engine

### ISSUE THREAD

**Issue by BhavyaLight** [BhavyaLight/information-retrival-search-engine#2]
Create a simple UI to enter your search. Should be flexible enough to add more features later. 
Preferable Django, but open to anything.

Question 2: Perform the following tasks:
• Build a simple Web interface for the search engine (e.g., Google)
• A simple UI for crawling and incremental indexing of new data would be a bonus (but not compulsory)
• Write five queries, get their results, and measure the speed of the querying

**Comment by noopurj** [comment]
commit - [basic ui](https://github.com/BhavyaLight/information-retrival-search-engine/commit/6448b341270139c973fbd9ffd3b07d18f31eabc8)
